"""migration

Revision ID: da6910dd8855
Revises: 
Create Date: 2021-08-27 08:51:28.341575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6910dd8855'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_notications',
    sa.Column('notifcation_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_dropped', sa.Boolean(), nullable=False),
    sa.Column('is_left', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('notification_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('notifcation_id')
    )
    op.create_table('parent_notications',
    sa.Column('notifcation_id', sa.Integer(), nullable=False),
    sa.Column('kid_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_dropped', sa.Boolean(), nullable=False),
    sa.Column('is_left', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('notification_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('notifcation_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('kid', sa.Boolean(), nullable=False),
    sa.Column('staff', sa.Boolean(), nullable=False),
    sa.Column('parent', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('parent_notications')
    op.drop_table('admin_notications')
    # ### end Alembic commands ###
